FROM node:17-buster-slim

WORKDIR /usr/src/app
COPY src/* .
COPY package.json .
COPY index.js .
COPY .env .

RUN ls /usr/src/app

RUN yarn

# Copy the code into the container
COPY . /usr/src/app

EXPOSE ${BACKEND_PORT}

CMD ["node", "./index.js", "&"]