version: '3.0'
services:
  db:
    container_name: '${MYSQL_HOST}'
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${MYSQL_DB}'
      MYSQL_ROOT: '${MYSQL_ROOT}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    expose: 
      - '${MYSQL_PORT}'
    volumes:
      - ./db:/var/lib/mysql

  app:
    container_name: ics_backend_app
    build: 
      context: .
      dockerfile: Dockerfile_api
    env_file: .env
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    expose: 
      - '${BACKEND_PORT}'
    depends_on:
      - db
    restart: unless-stopped